name = "Apricot Hugo Theme"
license = "MIT"
licenselink = "https://github.com/otterpro/apricot-hugo-theme/blob/master/LICENSE.md"
description = "Easy-to-read blog theme for Hugo"
homepage = "https://github.com/otterpro/apricot-hugo-theme/"
tags = ["blog","responsive"]
features = ["blog"]
min_version = "0.38.2"

[author]
  name = "Daniel Kim"
  homepage = "https://www.otter.pro/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
